### ISSUE TITLE
Safari browser support

### ISSUE THREAD

**Issue by gut4** [everywill/VideoEncoder#1]
Now it doesn't work in safari browser. 

/demo throw this error:
```
[Error] Unhandled Promise Rejection: CompileError: WebAssembly.Module doesn't parse at byte 107: invalid opcode 253, in function at index 24
	promiseEmptyOnRejected
	promiseReactionJob
```

**Comment by everywill** [comment]
It seems safari doesn't support SIMD opcode: v128.store64_lane.  Some more appropriate SIMD operation should be chosen.

**Comment by everywill** [comment]
libx264.a without SIMD provided first.
